// Data lokasi pins peta Indonesia — job inspeksi drone
export const pinData = [
  {
    id: 1,
    title: 'Inspeksi Menara SUTET 150kV',
    location: 'Cilegon, Banten',
    coordinates: [106.05, -6.02],
    status: 'urgent',
    type: 'Transmisi Listrik',
    budget: 'Rp 45.000.000',
    deadline: '3 Hari',
    postedAgo: '2 jam lalu',
    pilotNeeded: 2,
    province: 'Banten',
  },
  {
    id: 2,
    title: 'Survey Pipa Gas Bawah Laut',
    location: 'Balikpapan, Kaltim',
    coordinates: [116.85, -1.27],
    status: 'active',
    type: 'Migas & Energi',
    budget: 'Rp 120.000.000',
    deadline: '7 Hari',
    postedAgo: '5 jam lalu',
    pilotNeeded: 4,
    province: 'Kalimantan Timur',
  },
  {
    id: 3,
    title: 'Monitoring Bendungan Jatiluhur',
    location: 'Purwakarta, Jawa Barat',
    coordinates: [107.38, -6.53],
    status: 'active',
    type: 'Bendungan & Irigasi',
    budget: 'Rp 35.000.000',
    deadline: '5 Hari',
    postedAgo: '1 hari lalu',
    pilotNeeded: 1,
    province: 'Jawa Barat',
  },
  {
    id: 4,
    title: 'Inspeksi Jembatan Suramadu',
    location: 'Surabaya, Jawa Timur',
    coordinates: [112.78, -7.19],
    status: 'active',
    type: 'Jalan Tol & Jembatan',
    budget: 'Rp 78.000.000',
    deadline: '10 Hari',
    postedAgo: '3 jam lalu',
    pilotNeeded: 3,
    province: 'Jawa Timur',
  },
  {
    id: 5,
    title: 'Pemetaan Kilang Minyak Dumai',
    location: 'Dumai, Riau',
    coordinates: [101.45, 1.68],
    status: 'urgent',
    type: 'Migas & Energi',
    budget: 'Rp 95.000.000',
    deadline: '2 Hari',
    postedAgo: '30 menit lalu',
    pilotNeeded: 3,
    province: 'Riau',
  },
  {
    id: 6,
    title: 'Inspeksi Tower Telekomunikasi',
    location: 'Makassar, Sulawesi Selatan',
    coordinates: [119.43, -5.14],
    status: 'active',
    type: 'Transmisi Listrik',
    budget: 'Rp 28.000.000',
    deadline: '4 Hari',
    postedAgo: '6 jam lalu',
    pilotNeeded: 1,
    province: 'Sulawesi Selatan',
  },
  {
    id: 7,
    title: 'Survey Kawasan Industri Kendal',
    location: 'Semarang, Jawa Tengah',
    coordinates: [110.42, -6.97],
    status: 'active',
    type: 'Kawasan Industri',
    budget: 'Rp 52.000.000',
    deadline: '6 Hari',
    postedAgo: '12 jam lalu',
    pilotNeeded: 2,
    province: 'Jawa Tengah',
  },
  {
    id: 8,
    title: 'Monitoring Pasca Gempa Palu',
    location: 'Palu, Sulawesi Tengah',
    coordinates: [119.87, -0.90],
    status: 'urgent',
    type: 'Penanggulangan Bencana',
    budget: 'Rp 65.000.000',
    deadline: '1 Hari',
    postedAgo: '15 menit lalu',
    pilotNeeded: 5,
    province: 'Sulawesi Tengah',
  },
  {
    id: 9,
    title: 'Inspeksi Dermaga Pelabuhan',
    location: 'Tanjung Priok, Jakarta',
    coordinates: [106.88, -6.10],
    status: 'active',
    type: 'Pelabuhan',
    budget: 'Rp 42.000.000',
    deadline: '5 Hari',
    postedAgo: '4 jam lalu',
    pilotNeeded: 2,
    province: 'DKI Jakarta',
  },
  {
    id: 10,
    title: 'Survey Jalur Transmisi 500kV',
    location: 'Medan, Sumatera Utara',
    coordinates: [98.67, 3.59],
    status: 'urgent',
    type: 'Transmisi Listrik',
    budget: 'Rp 88.000.000',
    deadline: '2 Hari',
    postedAgo: '1 jam lalu',
    pilotNeeded: 3,
    province: 'Sumatera Utara',
  },
];

// Connection lines between project hubs
export const connectionLines = [
  { from: [106.05, -6.02], to: [107.38, -6.53] },
  { from: [107.38, -6.53], to: [110.42, -6.97] },
  { from: [110.42, -6.97], to: [112.78, -7.19] },
  { from: [112.78, -7.19], to: [119.43, -5.14] },
  { from: [119.43, -5.14], to: [119.87, -0.90] },
  { from: [116.85, -1.27], to: [119.87, -0.90] },
  { from: [101.45, 1.68], to: [98.67, 3.59] },
  { from: [106.05, -6.02], to: [106.88, -6.10] },
  { from: [101.45, 1.68], to: [106.05, -6.02] },
];

export const mapConfig = {
  accessToken: import.meta.env.VITE_MAPBOX_TOKEN,
  style: 'mapbox://styles/mapbox/satellite-streets-v12',
  center: [118.0, -2.5],
  zoom: 4.8,
  pitch: 40,
  bearing: -5,
  projection: 'globe',
};

export const statsData = [
  { value: 128, suffix: '+', label: 'Proyek Aktif', icon: 'briefcase', color: '#0062D6' },
  { value: 42, suffix: '', label: 'Pilot Online', icon: 'users', color: '#10B981' },
  { value: 19, suffix: '', label: 'Provinsi Tercover', icon: 'map', color: '#8B5CF6' },
  { value: 8, suffix: '', label: 'Proyek Urgent', icon: 'alert', color: '#F59E0B' },
];

export const liveAlerts = [
  { id: 1, message: 'Proyek baru: Inspeksi SUTET Cilegon', time: '2 menit lalu', type: 'new' },
  { id: 2, message: 'Pilot Andi diterima di proyek Suramadu', time: '5 menit lalu', type: 'accepted' },
  { id: 3, message: 'Urgent: Monitoring pasca gempa Palu', time: '15 menit lalu', type: 'urgent' },
  { id: 4, message: 'Laporan selesai: Survey Pipa Balikpapan', time: '22 menit lalu', type: 'completed' },
  { id: 5, message: 'Proyek baru: Pemetaan Kilang Dumai', time: '30 menit lalu', type: 'new' },
];
