export const pilots = [
 {
 id: 1,
 name: 'Rizky Pratama',
 location: 'Surabaya, Jawa Timur',
 specializations: ['SUTET', 'Migas'],
 drone: 'DJI Matrice 300 RTK',
 rating: 4.95,
 missions: 127,
 startingPrice: 'Rp 5jt',
 initials: 'RP',
 gradientBg: 'linear-gradient(135deg, #0062D6, #00B4D8)',
 },
 {
 id: 2,
 name: 'Andi Maulana',
 location: 'Bandung, Jawa Barat',
 specializations: ['Konstruksi', 'Survey'],
 drone: 'DJI Phantom 4 RTK',
 rating: 4.88,
 missions: 89,
 startingPrice: 'Rp 4jt',
 initials: 'AM',
 gradientBg: 'linear-gradient(135deg, #00897B, #00B4D8)',
 },
 {
 id: 3,
 name: 'Dewi Lestari',
 location: 'Jakarta',
 specializations: ['Solar Farm', 'Building'],
 drone: 'DJI Mavic 3 Enterprise',
 rating: 4.92,
 missions: 113,
 startingPrice: 'Rp 3,5jt',
 initials: 'DL',
 gradientBg: 'linear-gradient(135deg, #7c3aed, #0062D6)',
 },
 {
 id: 4,
 name: 'Fajar Nugroho',
 location: 'Balikpapan, Kalimantan Timur',
 specializations: ['Migas Offshore'],
 drone: 'Autel EVO Max 4T',
 rating: 4.97,
 missions: 156,
 startingPrice: 'Rp 8jt',
 initials: 'FN',
 gradientBg: 'linear-gradient(135deg, #0A2540, #0062D6)',
 },
 {
 id: 5,
 name: 'Bayu Saputra',
 location: 'Semarang, Jawa Tengah',
 specializations: ['Jembatan', 'Tol'],
 drone: 'DJI Matrice 30T',
 rating: 4.85,
 missions: 74,
 startingPrice: 'Rp 4,5jt',
 initials: 'BS',
 gradientBg: 'linear-gradient(135deg, #0062D6, #004aad)',
 },
 {
 id: 6,
 name: 'Sari Handayani',
 location: 'Medan, Sumatera Utara',
 specializations: ['Bendungan', 'Irigasi'],
 drone: 'DJI Mavic 3 Pro',
 rating: 4.90,
 missions: 102,
 startingPrice: 'Rp 4jt',
 initials: 'SH',
 gradientBg: 'linear-gradient(135deg, #00897B, #004aad)',
 },
 {
 id: 7,
 name: 'Reza Firmansyah',
 location: 'Makassar, Sulawesi Selatan',
 specializations: ['Mining', 'Quarry'],
 drone: 'DJI Matrice 300 RTK',
 rating: 4.93,
 missions: 138,
 startingPrice: 'Rp 6jt',
 initials: 'RF',
 gradientBg: 'linear-gradient(135deg, #0A2540, #00B4D8)',
 },
 {
 id: 8,
 name: 'Ahmad Wijaya',
 location: 'Pekanbaru, Riau',
 specializations: ['SUTET', 'BTS Tower'],
 drone: 'DJI Phantom 4 RTK',
 rating: 4.86,
 missions: 91,
 startingPrice: 'Rp 4,5jt',
 initials: 'AW',
 gradientBg: 'linear-gradient(135deg, #0062D6, #00897B)',
 },
];

export const filterCategories = [
 'Semua',
 'SUTET',
 'Migas',
 'Konstruksi',
 'Survey',
 'Mining',
];
