/**
 * Browse Pilots — Mock Data Module
 * Single source of truth for pilot data on the /pilots marketplace page.
 * Feature: browse-pilots
 */

export const SPECIALIZATION_OPTIONS = [
 'Infrastruktur',
 'FPV',
 'Pemetaan',
 'Fotografi',
 'Inspeksi Termal',
];

export const RATING_OPTIONS = [
 { label: '3+', value: 3 },
 { label: '4+', value: 4 },
 { label: '4.5+', value: 4.5 },
];

export const PROVINCE_OPTIONS = [
 'Aceh', 'Sumatera Utara', 'Sumatera Barat', 'Riau', 'Jambi',
 'Sumatera Selatan', 'Bengkulu', 'Lampung', 'Kepulauan Bangka Belitung',
 'Kepulauan Riau', 'DKI Jakarta', 'Jawa Barat', 'Jawa Tengah',
 'DI Yogyakarta', 'Jawa Timur', 'Banten', 'Bali',
 'Nusa Tenggara Barat', 'Nusa Tenggara Timur', 'Kalimantan Barat',
 'Kalimantan Tengah', 'Kalimantan Selatan', 'Kalimantan Timur',
 'Kalimantan Utara', 'Sulawesi Utara', 'Sulawesi Tengah',
 'Sulawesi Selatan', 'Sulawesi Tenggara', 'Gorontalo',
 'Sulawesi Barat', 'Maluku', 'Maluku Utara', 'Papua Barat', 'Papua',
];

export const pilots = [
 {
 id: 'PIL-001',
 name: 'Andi Pratama',
 city: 'Bandung',
 province: 'Jawa Barat',
 specializations: ['Infrastruktur', 'Inspeksi Termal'],
 rating: 4.95,
 siaga_verified: true,
 drone_type: 'DJI Matrice 300 RTK',
 drones: [
 { name: 'DJI Matrice 300 RTK', use_case: 'Thermal & structural inspection' },
 { name: 'DJI Mavic 3 Enterprise', use_case: 'Visual documentation' },
 ],
 projects_completed: 127,
 response_rate: '98%',
 avg_response_time: '12 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Top Rated', 'Infrastructure Expert'],
 portfolio_images: [
 {
 src: '/images/projects/sutet_bandung-cover-compressed.jpg',
 alt: 'Inspeksi SUTET 150kV Bandung Selatan',
 caption: 'Inspeksi SUTET 150kV Bandung Selatan',
 project_name: 'Inspeksi SUTET Bandung Selatan',
 infrastructure_type: 'Jaringan Transmisi Listrik',
 location: 'Bandung, Jawa Barat',
 inspection_type: 'Thermal Inspection',
 drone_used: 'DJI Matrice 300 RTK',
 date: '2026-01-15',
 },
 {
 src: '/images/projects/sutet_bandung-gallery_1-compressed.jpg',
 alt: 'Detail thermal SUTET',
 caption: 'Thermal anomaly detection pada isolator',
 project_name: 'Inspeksi SUTET Bandung Selatan',
 infrastructure_type: 'Jaringan Transmisi Listrik',
 location: 'Bandung, Jawa Barat',
 inspection_type: 'Thermal Inspection',
 drone_used: 'DJI Matrice 300 RTK',
 date: '2026-01-15',
 },
 {
 src: '/images/projects/sutet_bandung-gallery_2-compressed.jpg',
 alt: 'Inspeksi visual tower SUTET',
 caption: 'Visual inspection tower 47',
 project_name: 'Inspeksi SUTET Bandung Selatan',
 infrastructure_type: 'Jaringan Transmisi Listrik',
 location: 'Bandung, Jawa Barat',
 inspection_type: 'Visual Inspection',
 drone_used: 'DJI Matrice 300 RTK',
 date: '2026-01-16',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Hendra Wijaya',
 reviewer_avatar: '',
 rating: 5,
 text: 'Pilot sangat profesional, hasil thermal inspection sangat detail dan akurat. Rekomendasi untuk proyek SUTET.',
 date: '2026-02-10',
 },
 {
 reviewer_name: 'PT Infrastruktur Nusantara',
 reviewer_avatar: '',
 rating: 5,
 text: 'Response cepat, data inspeksi lengkap, dan laporan terstruktur. Sudah 3x kerja sama.',
 date: '2026-01-28',
 },
 ],
 bio: 'Pilot inspeksi infrastruktur berpengalaman 5 tahun dengan spesialisasi SUTET, jembatan, dan tower telekomunikasi. Tersertifikasi SIDOPI dan berpengalaman menggunakan sensor thermal untuk deteksi anomali.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-03-15', expiry_date: '2027-03-15', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Bandung', 'Garut', 'Sumedang', 'Cimahi', 'Cianjur'],
 member_since: '2024-01',
 avatar: '/images/avatars/Avatar 1.jpg',
 cover_image: '/images/projects/sutet_bandung-cover-compressed.jpg',
 },
 {
 id: 'PIL-002',
 name: 'Budi Santoso',
 city: 'Semarang',
 province: 'Jawa Tengah',
 specializations: ['Infrastruktur', 'Pemetaan'],
 rating: 4.88,
 siaga_verified: true,
 drone_type: 'DJI Phantom 4 RTK',
 drones: [
 { name: 'DJI Phantom 4 RTK', use_case: 'Orthomosaic mapping' },
 { name: 'DJI Mavic 3 Pro', use_case: 'Visual inspection' },
 ],
 projects_completed: 89,
 response_rate: '95%',
 avg_response_time: '18 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Fast Response'],
 portfolio_images: [
 {
 src: '/images/projects/tol_semarangsolo-cover-compressed.jpg',
 alt: 'Pemetaan jalan tol Semarang-Solo',
 caption: 'Pemetaan progress jalan tol Semarang-Solo',
 project_name: 'Monitoring Tol Semarang-Solo',
 infrastructure_type: 'Jalan Tol',
 location: 'Semarang, Jawa Tengah',
 inspection_type: 'Orthomosaic Mapping',
 drone_used: 'DJI Phantom 4 RTK',
 date: '2025-11-20',
 },
 {
 src: '/images/projects/tol_semarangsolo-gallery_1-compressed.jpg',
 alt: 'Detail mapping tol',
 caption: 'Orthomosaic section KM 12-15',
 project_name: 'Monitoring Tol Semarang-Solo',
 infrastructure_type: 'Jalan Tol',
 location: 'Semarang, Jawa Tengah',
 inspection_type: 'Orthomosaic Mapping',
 drone_used: 'DJI Phantom 4 RTK',
 date: '2025-11-21',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Dinas PU Jawa Tengah',
 reviewer_avatar: '',
 rating: 5,
 text: 'Hasil pemetaan sangat presisi, data orthomosaic membantu monitoring progress konstruksi.',
 date: '2025-12-05',
 },
 ],
 bio: 'Spesialis pemetaan udara dan monitoring konstruksi infrastruktur. Berpengalaman dalam proyek jalan tol, bendungan, dan kawasan industri di Jawa Tengah.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-06-01', expiry_date: '2027-06-01', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Semarang', 'Solo', 'Salatiga', 'Boyolali', 'Klaten'],
 member_since: '2024-03',
 avatar: '/images/avatars/Avatar 2.jpg',
 cover_image: '/images/projects/tol_semarangsolo-cover-compressed.jpg',
 },
 {
 id: 'PIL-003',
 name: 'Citra Lestari',
 city: 'Surabaya',
 province: 'Jawa Timur',
 specializations: ['Inspeksi Termal', 'Infrastruktur'],
 rating: 4.92,
 siaga_verified: true,
 drone_type: 'DJI Matrice 30T',
 drones: [
 { name: 'DJI Matrice 30T', use_case: 'Thermal & zoom inspection' },
 { name: 'Autel EVO Max 4T', use_case: 'Multi-sensor inspection' },
 ],
 projects_completed: 113,
 response_rate: '97%',
 avg_response_time: '10 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Top Rated', 'Thermal Certified'],
 portfolio_images: [
 {
 src: '/images/projects/tower_surakarta-cover-compressed.jpg',
 alt: 'Inspeksi thermal tower telekomunikasi',
 caption: 'Thermal inspection BTS Tower Surakarta',
 project_name: 'Inspeksi BTS Tower Surakarta',
 infrastructure_type: 'Menara Telekomunikasi',
 location: 'Surabaya, Jawa Timur',
 inspection_type: 'Thermal Inspection',
 drone_used: 'DJI Matrice 30T',
 date: '2026-02-08',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Telkom Infrastructure',
 reviewer_avatar: '',
 rating: 5,
 text: 'Hasil thermal sangat detail, bisa mendeteksi hotspot pada connector yang tidak terlihat secara visual.',
 date: '2026-02-20',
 },
 {
 reviewer_name: 'Ahmad Fauzi',
 reviewer_avatar: '',
 rating: 4.5,
 text: 'Profesional dan tepat waktu. Laporan inspeksi lengkap dengan rekomendasi maintenance.',
 date: '2026-01-15',
 },
 ],
 bio: 'Pilot wanita pertama di SIAGA dengan spesialisasi inspeksi thermal untuk tower telekomunikasi dan jaringan listrik. Berpengalaman mendeteksi anomali thermal pada komponen infrastruktur.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-01-10', expiry_date: '2027-01-10', badge_color: '#00B4D8', status: 'active' },
 { name: 'Thermal Imaging Level 2', issued_date: '2024-05-20', expiry_date: '2027-05-20', badge_color: '#F57C00', status: 'active' },
 ],
 area_operasi: ['Surabaya', 'Sidoarjo', 'Gresik', 'Mojokerto', 'Malang'],
 member_since: '2024-01',
 avatar: '/images/avatars/Avatar 3.jpg',
 cover_image: '/images/projects/tower_surakarta-cover-compressed.jpg',
 },
 {
 id: 'PIL-004',
 name: 'Dimas Ardiansyah',
 city: 'Wonogiri',
 province: 'Jawa Tengah',
 specializations: ['Infrastruktur', 'Pemetaan', 'Fotografi'],
 rating: 4.78,
 siaga_verified: true,
 drone_type: 'DJI Mavic 3 Enterprise',
 drones: [
 { name: 'DJI Mavic 3 Enterprise', use_case: 'Structural inspection' },
 ],
 projects_completed: 64,
 response_rate: '92%',
 avg_response_time: '25 menit',
 availability: 'Busy until next week',
 trust_badges: ['SIDOPI Active', 'Infrastructure Expert'],
 portfolio_images: [
 {
 src: '/images/projects/bendungan_gajahmungkur-cover-compressed.jpg',
 alt: 'Inspeksi Bendungan Gajahmungkur',
 caption: 'Monitoring struktural Bendungan Gajahmungkur',
 project_name: 'Inspeksi Bendungan Gajahmungkur',
 infrastructure_type: 'Bendungan',
 location: 'Wonogiri, Jawa Tengah',
 inspection_type: 'Structural Monitoring',
 drone_used: 'DJI Mavic 3 Enterprise',
 date: '2025-10-12',
 },
 {
 src: '/images/projects/bendungan_gajahmungkur-gallery_1-compressed.jpg',
 alt: 'Detail spillway bendungan',
 caption: 'Inspeksi spillway dan retakan mikro',
 project_name: 'Inspeksi Bendungan Gajahmungkur',
 infrastructure_type: 'Bendungan',
 location: 'Wonogiri, Jawa Tengah',
 inspection_type: 'Visual Inspection',
 drone_used: 'DJI Mavic 3 Enterprise',
 date: '2025-10-13',
 },
 {
 src: '/images/projects/bendungan_gajahmungkur-gallery_2-compressed.jpg',
 alt: 'Pemetaan area bendungan',
 caption: 'Orthomosaic area genangan',
 project_name: 'Inspeksi Bendungan Gajahmungkur',
 infrastructure_type: 'Bendungan',
 location: 'Wonogiri, Jawa Tengah',
 inspection_type: 'Orthomosaic Mapping',
 drone_used: 'DJI Mavic 3 Enterprise',
 date: '2025-10-14',
 },
 ],
 reviews: [
 {
 reviewer_name: 'BBWS Bengawan Solo',
 reviewer_avatar: '',
 rating: 5,
 text: 'Data inspeksi sangat membantu untuk evaluasi kondisi bendungan. Pilot kooperatif dan profesional.',
 date: '2025-11-01',
 },
 ],
 bio: 'Pilot inspeksi bendungan dan irigasi dengan pengalaman di proyek-proyek BBWS. Mampu melakukan pemetaan orthomosaic dan inspeksi visual struktural.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-08-01', expiry_date: '2027-08-01', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Wonogiri', 'Sukoharjo', 'Karanganyar', 'Sragen'],
 member_since: '2024-06',
 avatar: '/images/avatars/Avatar 4.jpg',
 cover_image: '/images/projects/bendungan_gajahmungkur-cover-compressed.jpg',
 },
 {
 id: 'PIL-005',
 name: 'Fajar Nugroho',
 city: 'Balikpapan',
 province: 'Kalimantan Timur',
 specializations: ['FPV', 'Infrastruktur'],
 rating: 4.97,
 siaga_verified: true,
 drone_type: 'Custom FPV 5-inch',
 drones: [
 { name: 'Custom FPV 5-inch', use_case: 'FPV close-range inspection' },
 { name: 'DJI Matrice 300 RTK', use_case: 'Long-range thermal' },
 ],
 projects_completed: 156,
 response_rate: '99%',
 avg_response_time: '8 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Top Rated', 'Fast Response'],
 portfolio_images: [
 {
 src: '/images/projects/barelang-cover-compressed.jpg',
 alt: 'FPV inspection jembatan Barelang',
 caption: 'FPV close-range inspection Jembatan Barelang',
 project_name: 'Inspeksi Jembatan Barelang',
 infrastructure_type: 'Jembatan',
 location: 'Batam, Kepulauan Riau',
 inspection_type: 'FPV Close-Range',
 drone_used: 'Custom FPV 5-inch',
 date: '2026-03-05',
 },
 {
 src: '/images/projects/barelang-gallery_1-compressed.jpg',
 alt: 'Detail struktur jembatan',
 caption: 'Inspeksi detail bearing pad',
 project_name: 'Inspeksi Jembatan Barelang',
 infrastructure_type: 'Jembatan',
 location: 'Batam, Kepulauan Riau',
 inspection_type: 'FPV Close-Range',
 drone_used: 'Custom FPV 5-inch',
 date: '2026-03-05',
 },
 {
 src: '/images/projects/barelang-gallery_2-compressed.jpg',
 alt: 'Inspeksi bawah deck jembatan',
 caption: 'Under-deck inspection via FPV',
 project_name: 'Inspeksi Jembatan Barelang',
 infrastructure_type: 'Jembatan',
 location: 'Batam, Kepulauan Riau',
 inspection_type: 'FPV Close-Range',
 drone_used: 'Custom FPV 5-inch',
 date: '2026-03-06',
 },
 ],
 reviews: [
 {
 reviewer_name: 'BP Batam',
 reviewer_avatar: '',
 rating: 5,
 text: 'Kemampuan FPV luar biasa, bisa masuk ke area yang tidak terjangkau drone biasa. Sangat direkomendasikan.',
 date: '2026-03-20',
 },
 {
 reviewer_name: 'Kementerian PUPR',
 reviewer_avatar: '',
 rating: 5,
 text: 'Pilot terbaik untuk inspeksi jembatan. FPV-nya sangat stabil dan hasilnya tajam.',
 date: '2026-02-15',
 },
 ],
 bio: 'Pilot FPV profesional dengan spesialisasi inspeksi close-range pada jembatan, pipa migas, dan struktur yang sulit dijangkau. Salah satu pilot FPV inspection terbaik di Indonesia.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2023-12-01', expiry_date: '2026-12-01', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Balikpapan', 'Samarinda', 'Batam', 'Pontianak'],
 member_since: '2023-12',
 avatar: '/images/avatars/Avatar 5.jpg',
 cover_image: '/images/projects/barelang-cover-compressed.jpg',
 },
 {
 id: 'PIL-006',
 name: 'Galih Permana',
 city: 'Medan',
 province: 'Sumatera Utara',
 specializations: ['Pemetaan', 'Fotografi'],
 rating: 4.65,
 siaga_verified: true,
 drone_type: 'DJI Phantom 4 RTK',
 drones: [
 { name: 'DJI Phantom 4 RTK', use_case: 'Topographic survey' },
 { name: 'DJI Air 3', use_case: 'Aerial photography' },
 ],
 projects_completed: 52,
 response_rate: '88%',
 avg_response_time: '30 menit',
 availability: 'Available next week',
 trust_badges: ['SIDOPI Active'],
 portfolio_images: [],
 reviews: [],
 bio: 'Pilot pemetaan dan fotografi udara berbasis di Medan. Berpengalaman dalam survey topografi untuk proyek perkebunan dan infrastruktur jalan.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2025-01-15', expiry_date: '2028-01-15', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Medan', 'Deli Serdang', 'Binjai', 'Langkat'],
 member_since: '2025-01',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-007',
 name: 'Hendra Kusuma',
 city: 'Makassar',
 province: 'Sulawesi Selatan',
 specializations: ['Infrastruktur', 'FPV', 'Inspeksi Termal'],
 rating: 4.82,
 siaga_verified: true,
 drone_type: 'DJI Matrice 300 RTK',
 drones: [
 { name: 'DJI Matrice 300 RTK', use_case: 'Industrial inspection' },
 { name: 'Custom FPV 7-inch', use_case: 'Confined space inspection' },
 ],
 projects_completed: 98,
 response_rate: '94%',
 avg_response_time: '15 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Infrastructure Expert', 'Fast Response'],
 portfolio_images: [
 {
 src: '/images/projects/barelang-gallery_3-compressed.jpg',
 alt: 'Inspeksi infrastruktur pelabuhan',
 caption: 'Inspeksi crane pelabuhan Makassar',
 project_name: 'Inspeksi Crane Pelabuhan',
 infrastructure_type: 'Pelabuhan',
 location: 'Makassar, Sulawesi Selatan',
 inspection_type: 'Structural Inspection',
 drone_used: 'DJI Matrice 300 RTK',
 date: '2025-09-18',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Pelindo IV',
 reviewer_avatar: '',
 rating: 5,
 text: 'Inspeksi crane sangat detail, pilot berpengalaman dan memahami keselamatan area pelabuhan.',
 date: '2025-10-02',
 },
 ],
 bio: 'Pilot inspeksi industri dengan pengalaman di pelabuhan, kilang minyak, dan infrastruktur berat di Indonesia Timur. Menguasai FPV untuk confined space.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-04-10', expiry_date: '2027-04-10', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Makassar', 'Pare-Pare', 'Bone', 'Maros'],
 member_since: '2024-04',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-008',
 name: 'Irfan Maulana',
 city: 'Pekanbaru',
 province: 'Riau',
 specializations: ['Pemetaan', 'Infrastruktur'],
 rating: 4.55,
 siaga_verified: false,
 drone_type: 'DJI Mavic 3 Pro',
 drones: [
 { name: 'DJI Mavic 3 Pro', use_case: 'Aerial survey' },
 ],
 projects_completed: 34,
 response_rate: '85%',
 avg_response_time: '45 menit',
 availability: 'Available this week',
 trust_badges: [],
 portfolio_images: [
 {
 src: '/images/projects/tol_semarangsolo-map-compressed.jpg',
 alt: 'Survey lahan perkebunan',
 caption: 'Survey lahan perkebunan sawit',
 project_name: 'Survey Perkebunan Riau',
 infrastructure_type: 'Perkebunan',
 location: 'Pekanbaru, Riau',
 inspection_type: 'Aerial Survey',
 drone_used: 'DJI Mavic 3 Pro',
 date: '2025-08-20',
 },
 ],
 reviews: [],
 bio: 'Pilot drone freelance di Riau dengan fokus pada pemetaan lahan dan monitoring infrastruktur perkebunan. Sedang dalam proses sertifikasi SIDOPI.',
 certifications: [],
 area_operasi: ['Pekanbaru', 'Dumai', 'Bengkalis'],
 member_since: '2025-06',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-009',
 name: 'Joko Widodo Putra',
 city: 'Yogyakarta',
 province: 'DI Yogyakarta',
 specializations: ['Fotografi', 'Pemetaan'],
 rating: 4.72,
 siaga_verified: true,
 drone_type: 'DJI Air 3',
 drones: [
 { name: 'DJI Air 3', use_case: 'Aerial photography' },
 { name: 'DJI Mini 4 Pro', use_case: 'Compact survey' },
 ],
 projects_completed: 78,
 response_rate: '91%',
 avg_response_time: '20 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Available this week'],
 portfolio_images: [],
 reviews: [
 {
 reviewer_name: 'Dinas Pariwisata DIY',
 reviewer_avatar: '',
 rating: 4.5,
 text: 'Hasil foto udara sangat bagus untuk dokumentasi candi dan situs heritage.',
 date: '2025-07-15',
 },
 ],
 bio: 'Pilot fotografi udara dan pemetaan ringan berbasis di Yogyakarta. Berpengalaman dalam dokumentasi heritage site dan monitoring konstruksi.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2025-02-01', expiry_date: '2028-02-01', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Yogyakarta', 'Sleman', 'Bantul', 'Kulon Progo'],
 member_since: '2025-02',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-010',
 name: 'Kevin Saputra',
 city: 'Denpasar',
 province: 'Bali',
 specializations: ['Fotografi', 'FPV'],
 rating: 4.60,
 siaga_verified: false,
 drone_type: 'DJI Mavic 3 Pro',
 drones: [
 { name: 'DJI Mavic 3 Pro', use_case: 'Cinematic aerial' },
 { name: 'Custom FPV 5-inch', use_case: 'FPV cinematic' },
 ],
 projects_completed: 45,
 response_rate: '87%',
 avg_response_time: '35 menit',
 availability: 'Busy until next month',
 trust_badges: [],
 portfolio_images: [
 {
 src: '/images/projects/barelang-cover_alt-compressed.jpg',
 alt: 'Aerial photography resort',
 caption: 'Dokumentasi aerial resort Bali',
 project_name: 'Dokumentasi Resort Nusa Dua',
 infrastructure_type: 'Properti',
 location: 'Denpasar, Bali',
 inspection_type: 'Aerial Photography',
 drone_used: 'DJI Mavic 3 Pro',
 date: '2025-12-10',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Resort Nusa Dua',
 reviewer_avatar: '',
 rating: 4.5,
 text: 'Hasil video dan foto sangat cinematic. Cocok untuk marketing material.',
 date: '2025-12-20',
 },
 ],
 bio: 'Pilot drone kreatif berbasis di Bali dengan fokus pada aerial photography dan FPV cinematic. Mulai beralih ke inspeksi infrastruktur.',
 certifications: [],
 area_operasi: ['Denpasar', 'Badung', 'Gianyar', 'Tabanan'],
 member_since: '2025-04',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-011',
 name: 'Lukman Hakim',
 city: 'Palembang',
 province: 'Sumatera Selatan',
 specializations: ['Infrastruktur', 'Inspeksi Termal', 'Pemetaan'],
 rating: 4.85,
 siaga_verified: true,
 drone_type: 'Autel EVO Max 4T',
 drones: [
 { name: 'Autel EVO Max 4T', use_case: 'Multi-sensor inspection' },
 { name: 'DJI Phantom 4 RTK', use_case: 'Precision mapping' },
 ],
 projects_completed: 91,
 response_rate: '96%',
 avg_response_time: '14 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Thermal Certified', 'Fast Response'],
 portfolio_images: [
 {
 src: '/images/projects/sutet_bandung-gallery_3-compressed.jpg',
 alt: 'Inspeksi pipa migas',
 caption: 'Thermal inspection pipeline Pertamina',
 project_name: 'Inspeksi Pipeline Pertamina',
 infrastructure_type: 'Pipa Migas',
 location: 'Palembang, Sumatera Selatan',
 inspection_type: 'Thermal Inspection',
 drone_used: 'Autel EVO Max 4T',
 date: '2026-01-08',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Pertamina EP',
 reviewer_avatar: '',
 rating: 5,
 text: 'Pilot handal untuk inspeksi pipeline. Sensor thermal Autel sangat efektif mendeteksi kebocoran.',
 date: '2026-01-25',
 },
 {
 reviewer_name: 'PLN UP3 Palembang',
 reviewer_avatar: '',
 rating: 4.5,
 text: 'Kerjasama yang baik untuk inspeksi jaringan distribusi listrik.',
 date: '2025-11-30',
 },
 ],
 bio: 'Pilot multi-sensor inspection berbasis di Palembang. Spesialisasi pada inspeksi pipa migas, jaringan listrik, dan infrastruktur energi menggunakan Autel EVO Max 4T.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-02-20', expiry_date: '2027-02-20', badge_color: '#00B4D8', status: 'active' },
 { name: 'Thermal Imaging Level 1', issued_date: '2024-07-10', expiry_date: '2027-07-10', badge_color: '#F57C00', status: 'active' },
 ],
 area_operasi: ['Palembang', 'Prabumulih', 'Muara Enim', 'Ogan Ilir'],
 member_since: '2024-02',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-012',
 name: 'Muhammad Rizky',
 city: 'Jakarta',
 province: 'DKI Jakarta',
 specializations: ['Infrastruktur', 'Pemetaan', 'Fotografi'],
 rating: 4.90,
 siaga_verified: true,
 drone_type: 'DJI Matrice 300 RTK',
 drones: [
 { name: 'DJI Matrice 300 RTK', use_case: 'Industrial inspection' },
 { name: 'DJI Mavic 3 Enterprise', use_case: 'Quick survey' },
 { name: 'DJI Air 3', use_case: 'Documentation' },
 ],
 projects_completed: 142,
 response_rate: '97%',
 avg_response_time: '9 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Top Rated', 'Fast Response', 'Infrastructure Expert'],
 portfolio_images: [
 {
 src: '/images/projects/sutet_bandung-map-compressed.jpg',
 alt: 'Inspeksi gedung bertingkat Jakarta',
 caption: 'Facade inspection gedung perkantoran',
 project_name: 'Inspeksi Facade Gedung Sudirman',
 infrastructure_type: 'Gedung Bertingkat',
 location: 'Jakarta, DKI Jakarta',
 inspection_type: 'Visual Inspection',
 drone_used: 'DJI Matrice 300 RTK',
 date: '2026-02-28',
 },
 {
 src: '/images/projects/bendungan_gajahmungkur-map-compressed.jpg',
 alt: 'Pemetaan area konstruksi',
 caption: 'Progress monitoring konstruksi MRT',
 project_name: 'Monitoring MRT Jakarta Phase 3',
 infrastructure_type: 'Transportasi',
 location: 'Jakarta, DKI Jakarta',
 inspection_type: 'Progress Monitoring',
 drone_used: 'DJI Mavic 3 Enterprise',
 date: '2026-03-10',
 },
 ],
 reviews: [
 {
 reviewer_name: 'PT MRT Jakarta',
 reviewer_avatar: '',
 rating: 5,
 text: 'Pilot sangat profesional dan berpengalaman. Data monitoring progress sangat membantu tim konstruksi.',
 date: '2026-03-15',
 },
 {
 reviewer_name: 'Gedung Sudirman Tower',
 reviewer_avatar: '',
 rating: 5,
 text: 'Inspeksi facade cepat dan akurat. Bisa mendeteksi kerusakan yang tidak terlihat dari bawah.',
 date: '2026-03-05',
 },
 ],
 bio: 'Pilot senior berbasis di Jakarta dengan pengalaman 6 tahun di inspeksi infrastruktur urban. Menangani proyek gedung bertingkat, MRT, jalan layang, dan infrastruktur perkotaan.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2023-06-01', expiry_date: '2026-06-01', badge_color: '#00B4D8', status: 'active' },
 ],
 area_operasi: ['Jakarta Pusat', 'Jakarta Selatan', 'Tangerang', 'Bekasi', 'Depok'],
 member_since: '2023-06',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-013',
 name: 'Nanda Prasetyo',
 city: 'Manado',
 province: 'Sulawesi Utara',
 specializations: ['Pemetaan', 'Fotografi'],
 rating: 3.95,
 siaga_verified: false,
 drone_type: 'DJI Mini 4 Pro',
 drones: [
 { name: 'DJI Mini 4 Pro', use_case: 'Lightweight survey' },
 ],
 projects_completed: 18,
 response_rate: '80%',
 avg_response_time: '60 menit',
 availability: 'Available this week',
 trust_badges: [],
 portfolio_images: [],
 reviews: [],
 bio: 'Pilot drone pemula berbasis di Manado. Fokus pada pemetaan lahan dan fotografi udara untuk proyek lokal.',
 certifications: [],
 area_operasi: ['Manado', 'Tomohon', 'Bitung'],
 member_since: '2025-09',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-014',
 name: 'Oscar Tanujaya',
 city: 'Pontianak',
 province: 'Kalimantan Barat',
 specializations: ['Infrastruktur', 'Pemetaan'],
 rating: 3.80,
 siaga_verified: false,
 drone_type: 'DJI Mavic 3 Pro',
 drones: [
 { name: 'DJI Mavic 3 Pro', use_case: 'General survey' },
 ],
 projects_completed: 22,
 response_rate: '82%',
 avg_response_time: '50 menit',
 availability: 'Available next week',
 trust_badges: [],
 portfolio_images: [
 {
 src: '/images/projects/bendungan_gajahmungkur-map_alt-compressed.jpg',
 alt: 'Survey jalan kabupaten',
 caption: 'Survey kondisi jalan kabupaten',
 project_name: 'Survey Jalan Kabupaten Kubu Raya',
 infrastructure_type: 'Jalan',
 location: 'Pontianak, Kalimantan Barat',
 inspection_type: 'Aerial Survey',
 drone_used: 'DJI Mavic 3 Pro',
 date: '2025-07-22',
 },
 ],
 reviews: [
 {
 reviewer_name: 'Dinas PU Kalbar',
 reviewer_avatar: '',
 rating: 4,
 text: 'Cukup baik untuk survey jalan. Perlu peningkatan pada kualitas data GCP.',
 date: '2025-08-10',
 },
 ],
 bio: 'Pilot drone di Kalimantan Barat yang fokus pada survey infrastruktur jalan dan jembatan. Sedang mengembangkan kemampuan inspeksi thermal.',
 certifications: [],
 area_operasi: ['Pontianak', 'Kubu Raya', 'Mempawah'],
 member_since: '2025-05',
 avatar: '',
 cover_image: '',
 },
 {
 id: 'PIL-015',
 name: 'Putri Rahayu',
 city: 'Bandung',
 province: 'Jawa Barat',
 specializations: ['Inspeksi Termal', 'Fotografi', 'Pemetaan'],
 rating: 4.70,
 siaga_verified: true,
 drone_type: 'DJI Mavic 3 Thermal',
 drones: [
 { name: 'DJI Mavic 3 Thermal', use_case: 'Thermal survey' },
 { name: 'DJI Air 3', use_case: 'Visual documentation' },
 ],
 projects_completed: 56,
 response_rate: '93%',
 avg_response_time: '16 menit',
 availability: 'Available this week',
 trust_badges: ['SIDOPI Active', 'Thermal Certified', 'Available this week'],
 portfolio_images: [
 {
 src: '/images/projects/sutet_bandung-cover-compressed.jpg',
 alt: 'Inspeksi solar panel farm',
 caption: 'Thermal inspection solar panel farm',
 project_name: 'Inspeksi Solar Farm Cirata',
 infrastructure_type: 'Energi Terbarukan',
 location: 'Purwakarta, Jawa Barat',
 inspection_type: 'Thermal Inspection',
 drone_used: 'DJI Mavic 3 Thermal',
 date: '2026-02-01',
 },
 ],
 reviews: [
 {
 reviewer_name: 'PT Solar Cirata',
 reviewer_avatar: '',
 rating: 5,
 text: 'Inspeksi thermal panel surya sangat efisien. Bisa mendeteksi cell yang underperform dengan cepat.',
 date: '2026-02-15',
 },
 ],
 bio: 'Pilot inspeksi thermal wanita berbasis di Bandung. Spesialisasi pada inspeksi solar panel farm, rooftop solar, dan jaringan listrik menggunakan sensor thermal.',
 certifications: [
 { name: 'SIDOPI', issued_date: '2024-09-01', expiry_date: '2027-09-01', badge_color: '#00B4D8', status: 'active' },
 { name: 'Thermal Imaging Level 1', issued_date: '2024-11-15', expiry_date: '2027-11-15', badge_color: '#F57C00', status: 'active' },
 ],
 area_operasi: ['Bandung', 'Purwakarta', 'Subang', 'Karawang'],
 member_since: '2024-09',
 avatar: '',
 cover_image: '',
 },
];
